//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekSafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Items()
        {
            this.TransactionHistory = new HashSet<TransactionHistory>();
        }
    
        public int itemID { get; set; }
        public string userIDNum { get; set; }
        public string itemName { get; set; }
        public string itemType { get; set; }
        public string itemStatus { get; set; }
        public string itemDescription { get; set; }
        public Nullable<int> locationFound { get; set; }
        public Nullable<System.DateTime> dateFound { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ItemLocations ItemLocations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionHistory> TransactionHistory { get; set; }
    }
}
