//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekSafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public int transactionID { get; set; }
        public string userIDNum { get; set; }
        public string otherUserIDNum { get; set; }
        public Nullable<int> itemID { get; set; }
        public Nullable<System.DateTime> transactionDate { get; set; }
        public string transactionType { get; set; }
    
        public virtual Items Items { get; set; }
    }
}
