//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekSafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int userInfoID { get; set; }
        public string userIDNum { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<int> departmentID { get; set; }
        public string contactNo { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
    
        public virtual Departments Departments { get; set; }
    }
}
