//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekSafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccounts
    {
        public int userID { get; set; }
        public string userIDNum { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> roleID { get; set; }
    
        public virtual UserRoles UserRoles { get; set; }
    }
}
